# Generated by Django 5.2.1 on 2025-08-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_approve_post', 'Can approve posts')]},
        ),
    ]
